version: "3.8"
services:
  vue:
    build: ./vue
    volumes:
    - ./vue:/vue
    ports:
    - "8080:8080"
  vue_develop:
    build: ./vue_develop
    stdin_open: true
    tty: true
    volumes:
    - ./vue:/app
    user: "${UID}:${GID}"
    profiles: ["development"]
