version: "3.8"
services:
  express:
    build: ./express
    volumes:
    - images:/images
    - converted-images:/converted-images
  vue:
    build: ./vue
    volumes:
    - ./vue/vue-app/src:/vue/vue-app/src
  npm:
    build: ./npm
    volumes:
    - ./:/app
    user: "${UID}:${GID}"
    profiles:
      - "development"
  nginx:
    build: ./nginx
    ports:
    - "8080:8080"
    - "8081:8081"
  webp-converter:
    build: ./webp-converter
    volumes:
    - images:/images
    - converted-images:/converted-images

volumes:
  images:
  converted-images:
  movies:
