version: "3.8"
services:
  vue:
    build: ./vue
    volumes:
    - ./vue/vue-app/src:/vue/vue-app/src
  npm:
    build: ./npm
    volumes:
    - ./vue/vue-app:/vue/vue-app
  nginx:
    build: ./nginx
    ports:
    - "8080:8080"
