version: "3.8"
services:
  express:
    build: ./express
    volumes:
      - ./express/src/:/app/src
      - shared-volume:/app/shared-volume
  vue:
    build: ./vue
    volumes:
      - ./vue/vue-app/src:/vue/vue-app/src
  npm:
    build: ./npm
    volumes:
      - ./:/app
    profiles:
      - development
    user: "${UID}:${GID}"
  nginx:
    build: ./nginx
    ports:
      - "8080:8080"
      - "8081:8081"
  webp-converter:
    build: ./webp-converter
    volumes:
      - ./webp-converter/code/express/src:/code/express/src
      - shared-volume:/code/express/shared-volume

volumes:
  shared-volume:
